# Name des Workflows
name: Fetch iCal Feed

# Trigger: Wann soll dieser Workflow laufen?
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

# *** HIER IST DIE WICHTIGE ÄNDERUNG ***
# Gibt dem Workflow die Erlaubnis, Dateien ins Repository zu schreiben.
permissions:
  contents: write

# Die Jobs, die ausgeführt werden sollen
jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Fetch iCal feed
        run: |
          curl -o calendar.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical'

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update iCal feed"
          file_pattern: calendar.ics
