# Name des Workflows
name: Fetch iCal Feeds (Multiple)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # Ruft jeden Kalender einzeln mit dem korrekten Link ab
      - name: Fetch Calendar Feeds
        run: |
          curl -o gottesdienst.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical&security=JhLMtW3mMC2UnhpG6W6eBOpeCHBl4EhX&id=2'
          curl -o kinder.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical&security=jm55wpiL4j6xVOGHe5LAoydUISYWCucf&id=10'
          curl -o senioren.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical&security=6orvhiXu4Grihtp7LigljFAoRhNbVr70&id=33'
          curl -o jugend.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical&security=JKyPzzmVEYVaRac65whlhxEty8RLN3vz&id=3'
          curl -o sonstige.ics 'https://gemeindekonkordia.church.tools/?q=churchcal/ical&security=HpOp2CtkDW4MgLLFVsDfTeCuSCw3GpkG&id=1'

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update iCal feeds"
          file_pattern: '*.ics'
